name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
      
    - name: Cache Next.js build
      uses: actions/cache@v3
      with:
        path: |
          .next/cache
        key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
        restore-keys: |
          ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-
    
    - name: Check for required secrets
      run: |
        if [ -z "${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}" ] || [ -z "${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}" ]; then
          echo "Warning: Some Supabase environment variables are missing. This might affect the build."
        fi
        if [ -z "${{ secrets.NEXT_PUBLIC_AZURE_FORM_ENDPOINT }}" ] || [ -z "${{ secrets.NEXT_PUBLIC_AZURE_FORM_KEY }}" ]; then
          echo "Warning: Some Azure Form environment variables are missing. This might affect the build."
        fi
    
    - name: Lint
      run: npm run lint
      
    - name: Type check
      run: tsc --noEmit
      
    - name: Run tests
      run: npm test || true # Remove '|| true' once you have tests
      
    - name: Build
      run: npm run build
      env:
        NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL || 'dummy-value-for-pr' }}
        NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY || 'dummy-value-for-pr' }}
        NEXT_PUBLIC_AZURE_FORM_ENDPOINT: ${{ secrets.NEXT_PUBLIC_AZURE_FORM_ENDPOINT || 'dummy-value-for-pr' }}
        NEXT_PUBLIC_AZURE_FORM_KEY: ${{ secrets.NEXT_PUBLIC_AZURE_FORM_KEY || 'dummy-value-for-pr' }}
        NEXT_PUBLIC_AZURE_CV_KEY: ${{ secrets.NEXT_PUBLIC_AZURE_CV_KEY || 'dummy-value-for-pr' }}
        NEXT_PUBLIC_AZURE_CV_ENDPOINT: ${{ secrets.NEXT_PUBLIC_AZURE_CV_ENDPOINT || 'dummy-value-for-pr' }}
    
    - name: Check bundle size
      run: npm run analyze || true # Remove '|| true' once you set up bundle analysis 