name: Update Repository Secrets
on:
  workflow_dispatch:

jobs:
  update-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Update Secrets
        uses: gliech/create-github-secret-action@v1
        with:
          name: NEXT_PUBLIC_SUPABASE_URL
          value: https://zuajrsvhimnoefuzklry.supabase.co
          pa_token: ${{ secrets.GH_PA_TOKEN }}
          
      - name: Update Supabase Anon Key
        uses: gliech/create-github-secret-action@v1
        with:
          name: NEXT_PUBLIC_SUPABASE_ANON_KEY
          value: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
          pa_token: ${{ secrets.GH_PA_TOKEN }}
          
      - name: Update Azure Form Endpoint
        uses: gliech/create-github-secret-action@v1
        with:
          name: NEXT_PUBLIC_AZURE_FORM_ENDPOINT
          value: https://restaurantocr.cognitiveservices.azure.com/
          pa_token: ${{ secrets.GH_PA_TOKEN }}
          
      - name: Update Azure Form Key
        uses: gliech/create-github-secret-action@v1
        with:
          name: NEXT_PUBLIC_AZURE_FORM_KEY
          value: ${{ secrets.NEXT_PUBLIC_AZURE_FORM_KEY }}
          pa_token: ${{ secrets.GH_PA_TOKEN }}
          
      - name: Update Azure CV Key
        uses: gliech/create-github-secret-action@v1
        with:
          name: NEXT_PUBLIC_AZURE_CV_KEY
          value: ${{ secrets.NEXT_PUBLIC_AZURE_CV_KEY }}
          pa_token: ${{ secrets.GH_PA_TOKEN }}
          
      - name: Update Azure CV Endpoint
        uses: gliech/create-github-secret-action@v1
        with:
          name: NEXT_PUBLIC_AZURE_CV_ENDPOINT
          value: https://restaurantocr.cognitiveservices.azure.com/
          pa_token: ${{ secrets.GH_PA_TOKEN }}