name: Verify Secrets

on: workflow_dispatch

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Check Required Secrets
        run: |
          missing_secrets=()
          
          # Vercel Secrets
          [ -z "${{ secrets.VERCEL_TOKEN }}" ] && missing_secrets+=("VERCEL_TOKEN")
          [ -z "${{ secrets.VERCEL_ORG_ID }}" ] && missing_secrets+=("VERCEL_ORG_ID")
          [ -z "${{ secrets.VERCEL_PROJECT_ID }}" ] && missing_secrets+=("VERCEL_PROJECT_ID")
          
          # Supabase Secrets
          [ -z "${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}" ] && missing_secrets+=("NEXT_PUBLIC_SUPABASE_URL")
          [ -z "${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}" ] && missing_secrets+=("NEXT_PUBLIC_SUPABASE_ANON_KEY")
          
          # Azure Secrets
          [ -z "${{ secrets.NEXT_PUBLIC_AZURE_FORM_ENDPOINT }}" ] && missing_secrets+=("NEXT_PUBLIC_AZURE_FORM_ENDPOINT")
          [ -z "${{ secrets.NEXT_PUBLIC_AZURE_FORM_KEY }}" ] && missing_secrets+=("NEXT_PUBLIC_AZURE_FORM_KEY")
          [ -z "${{ secrets.NEXT_PUBLIC_AZURE_CV_KEY }}" ] && missing_secrets+=("NEXT_PUBLIC_AZURE_CV_KEY")
          [ -z "${{ secrets.NEXT_PUBLIC_AZURE_CV_ENDPOINT }}" ] && missing_secrets+=("NEXT_PUBLIC_AZURE_CV_ENDPOINT")
          
          if [ ${#missing_secrets[@]} -ne 0 ]; then
            echo "❌ Missing required secrets:"
            printf '%s\n' "${missing_secrets[@]}"
            exit 1
          else
            echo "✅ All required secrets are present"
          fi 